### ISSUE TITLE
GPL license violation

### ISSUE THREAD

**Issue by asiekierka** [Chisel-2/Chisel-3#1]
I am afraid this repository violates my copyright for Chisel versions 1.5.1-1.5.3 for Minecraft 1.7.2. The source code for them was provided under the [GNU GPL version 2](https://github.com/asiekierka/Chisel-1.7.2/blob/master/LICENSE), which is being violated in section 2b (modified version distributed under a license incompatible with the terms of the GPL). As per section 5 and the fact I have not granted permission for you to distribute source code of the Chisel version you derived from, you are required to comply under the terms of the GPL, which your license is not.

Please note that even if you modify the source code to the point of unrecognizability, this still constitutes a modified version of the source code and is still under the GPL's terms, unless you do a clean room rewrite of the source code as to not base on code from the Chisel project.

Examples of proof:

* [#1](https://github.com/asiekierka/Chisel-1.7.2/blame/master/src/main/java/info/jbcs/minecraft/chisel/entity/EntityBallOMoss.java) is nearly identical to the version in your codebase.
* [#2](https://github.com/asiekierka/Chisel-1.7.2/blob/master/src/main/java/info/jbcs/minecraft/chisel/entity/EntityCloudInABottle.java)

Further directly infringing classes cannot be provided as these, while derived from my codebase and thus also under the GPL, are primarily owned by different people and I leave it to them to take the necessary action.

On top of that, the legal status of bundling GPL-only artwork and language files with non-GPL code is unclear.

**Comment by TheCricket** [comment]
Next people are going to claim that metadata is part of it. This is how it has to be done with minecraft code there is no other way around it. I can change the shape of spawning but coding an item that you throw and spawn a cloud or change blocks to mossy is only written one way. The status of the art and lang is made very clear in 1.b So tell me, what would you like to be do about minecraft code? Because that is what we are dealing with. You literally cannot do this another way.

**Comment by asiekierka** [comment]
The status of art and lang, yes, but the status of bundling art and lang with your codebase is not clearly defined by the GPL which might cause problems. You can't just say "I'm doing X to Y" without Y also allowing you to do X.

My main issue is that all of the logic is laid out in exactly the same order with similar variable names. Code derived from Minecraft only is unlikely to look *exactly* the same. There's also other issues, but I am not the copyright holder for them.

**Comment by TheCricket** [comment]
So what would you like me to do with the two entities

**Comment by asiekierka** [comment]
Honestly? I don't care about those two specific entities. Do whatever you want, just know that you don't have my support for what you're doing.

I'm just pointing out that what you're doing is pulling a coup d'etat on an open-source mod - like MrTJP had done with Project: Red until 4.0.0. I won't stand for that, especially as it is a mod I contributed to back in the day.

As for the status of art/lang, you might be lucky:

>Since the FSF has clarified that use of art does not trigger the GPL's linking requirement, the LGPL is effectively the same as the GPL when used for art.

**Comment by TheCricket** [comment]
Not lucky. Planned

**Comment by asiekierka** [comment]
What about this bit?

>These requirements apply to the modified work as a whole.  If
>identifiable sections of that work are not derived from the Program,
>and can be reasonably considered independent and separate works in
>themselves, then this License, and its terms, do not apply to those
>sections when you distribute them as separate works.  But when you
>distribute **the same sections as part of a whole which is a work based**
>**on the Program, the distribution of the whole must be on the terms of**
>**this License, whose permissions for other licensees extend to the**
>**entire whole, and thus to each and every part regardless of who wrote it.**

**Comment by tterrag1098** [comment]
There is a HUGE difference between rewriting logic and having it end up looking similar, and copying a class and modifying it slightly. You have obviously done the latter. I posted these diffs on twitter but it is worth posting them again here.

https://www.diffnow.com/?report=4vdcz
https://www.diffnow.com/?report=nob8p

You can clearly see that the lines match up, you have simply changed variable names. This is unacceptable to me, and only serves to tell me that you knew copying the class was wrong so you tried to obfuscate it. Consider me of the same opinion as asie.
