### ISSUE TITLE
Question: Texture Permissions

### ISSUE THREAD

**Issue by DrakoAlcarus** [Chisel-2/Chisel-3#7]
This isn't mush as a suggestion, as it is me not knowing where to ask.

Can I borrow a few of the textures from your mod? It's for a mod I am making that adds in a few blocks for construction and machines to construct. I only need very few textures, as it can act as a simplistic chisel with recipes instead of a chisel. If your mod is installed, it completely overrides the blocks your mod may have.
 
The mod itself is a Thermal Expansion addon, and I may end up making a website, since I have four other mods in development. There is a chance that I may get money from hosting the download links, but I intend to give you full credit either way. If you need to see what textures I may use, let me know.

**Comment by TheCricket** [comment]
nope

**Comment by DrakoAlcarus** [comment]
Fair enough.

**Comment by asiekierka** [comment]
You can borrow textures from this older version as long as you mind the license (GPLv2): https://github.com/asiekierka/Chisel
